- rockcraft.yaml
Fix `rockcraft.yaml`:
- Fix license.
- Replace `entrypoint` with `services`
> Fix rockcraft.yaml

- main.go
- main_test.go
- ory_mocking/Handlers/handlers.go
- ory_mocking/Testservers/testservers.go
- ui/components/Logo.tsx
- ui/components/hydra.ts
- ui/components/sdk.ts
- ui/next.config.js
- ui/pages/consent.tsx
- ui/pages/login.tsx
When the UI is served behind a reverse proxy (e.g. traefik), the pages may be served under a subpath. This breaks our redirects and calls to the backend API. In order to overcome this we use relative paths everywhere.
This is not the proper solution and ideally we would want the reverse proxy to inject the html with the base URL tag.
> Use relative paths in redirects

- health/health.go
- main.go
- main_test.go
- ory_mocking/Handlers/handlers.go
- ory_mocking/Testservers/testservers.go
The purpose of this PR is to implement a liveness check for Login UI. It is accessible on the endpoint /health/alive. If the server is running, liveness check returns with '{'status':'ok'}'.
The pr includes the health.go library that exposes the handler for the liveness check. It also includes a handler for a readiness check which is not used in main, and is only there for possible future usage.
The pr also includes unit tests for the liveness check.
Additionally the pr includes mocked health checks for the mocked ory servers used for unit tests.
- health library implementing an API to store alive and ready statuses independently
- main.go implementing liveness check only
- tests liveness checks
- Handlers for mocking health checks
- mocked servers implementing health check mocking
This …
> IAM-307 Liveness check implementation

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
IAM-356: use separate token to overcome gh action block on recursive wokrflow creation
- ci: allow manual triggering of workflows
- ci: use different token to create releases
> IAM-356: release/token

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
The redirect response was causing the XHR request to fail because it would get redirected to Hydra and get a CORS error.
> Change response status to 200

- pkg/ui/handlers.go
- ui/api/hydra.ts
- ui/api/kratos.ts
Fixed bug, where the server treats all misc. routes as fileserver requests.
Try it out by compiling the app, and requesting different routes.
After that if you access /api/v0/metrics, you'll see that the server only added the .html extension to the routes corresponding to the embedded html files.
> IAM-386-Fix-Route-Matching bug

- internal/hydra/client.go
- internal/kratos/client.go
- pkg/status/handlers.go
- pkg/status/handlers_test.go
- pkg/status/interfaces.go
- pkg/status/service.go
- pkg/status/service_test.go
- pkg/web/router.go
Added the deep health check feature:
To manually test:
- Compile and run app with valid envvars for PORT, KRATOS_PUBLIC_URL, HYDRA_ADMIN_URL
- For urls use format: http://ip:port
- Send get request to the endpoint /api/v0/deepcheck
> IAM-398-Added deep health check

- ui/pages/consent.tsx
The relative paths in the consent page have been updated to account for the change in the ui resources endpoints.
> Fixed bug in consent page

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- pkg/kratos/interfaces.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- ui/pages/login.tsx
IAM-349:
- Convert Kratos 422 responses to  200 in the `UpdateLoginFlow` endpoint.
- Update the UI to handle the new response.
> Tranform Kratos 422 HTTP resp to 200

- .github/workflows/release.yaml
- cmd/main.go
- internal/config/specs.go
- internal/config/version.go
- internal/version/const.go
- pkg/status/service.go
IAM-494
This PR:
- Adds CLI flags to the app
- Allows to inject the app version via ldflags
- Updates the status endpoint with information about the git commit hash
```console
$ APP_VERSION=42 make build 
make -C cmd build
make[1]: Entering directory '/home/nikos/projects/identity-platform-login-ui/cmd'
go build -ldflags "-X github.com/canonical/identity-platform-login-ui/internal/config.Version=42" -o app ./
make[1]: Leaving directory '/home/nikos/projects/identity-platform-login-ui/cmd'
$ ./cmd/app -version
App Version: 42
```
> Expose app version

- docker/kratos/kratos.yml
- ui/components/NodeInput.tsx
Use the label received from kratos to generate the button text when asking the user to choose a provider. Relevant PR https://github.com/canonical/kratos-external-idp-integrator/pull/61
> Use label to generate button text

- structure-tests.yaml
Fix container structure tests (bug was introduced by the refactor of the CLI)
Question:
Should we add tests for the rest of the commands?
> Fix container structure tests

- docker/hydra/hydra.yml
- go.mod
- go.sum
- internal/hydra/client.go
- internal/hydra/device.go
- internal/hydra/interfaces.go
- pkg/device/handlers.go
- pkg/device/handlers_test.go
- pkg/device/interfaces.go
- pkg/device/service.go
- pkg/device/service_test.go
- pkg/extra/interfaces.go
- pkg/extra/service_test.go
- pkg/kratos/interfaces.go
- pkg/kratos/service_test.go
- pkg/web/router.go
- ui/pages/device_code.tsx
IAM-736:
- Update the device code page.
There are a couple problems with this PR:
- We do not use the Hydra sdk to call the Hydra API. If we wish to use the client sdk do we have to fork https://github.com/ory/hydra-client-go?
- It does not handle errors from the backend. If the user inputs a wrong code, then nothing happens
- From a UX perspective it would be better if we had one box per letter rather than a single box for the whole code, e.g. see netflix:
> Update device code page

- ui/package-lock.json
- ui/pages/device_complete.tsx
Added success screen for device flow under the url http://localhost:4455/ui/device_complete
Fixes: WD-10251
> Add success screen for device flow WD-10251

- docker/hydra/hydra.yml
- internal/misc/http/helpers.go
- pkg/extra/service.go
- pkg/extra/service_test.go
IAM-909
Add client_id to access token's audience.
Before the change, a jwt access token would be
```
eyJhbGciOiJSUzI1NiIsImtpZCI6ImIwN2JkYTU2LTMyMmYtNGQ0Yi1hOTFiLWRmZjFlZjhiNjMyNyIsInR5cCI6IkpXVCJ9.eyJhdWQiOltdLCJjbGllbnRfaWQiOiI0NmQ3MjExNC0zYmRmLTQ0ZTItYjEzZC04NmMyY2NjOWUzNzUiLCJleHAiOjE3MTk5MzAyMDAsImV4dCI6e30sImlhdCI6MTcxOTkyNjU5OSwiaXNzIjoiaHR0cDovL2h5ZHJhOjQ0NDQiLCJqdGkiOiI3NmQyYzM4ZC01YjVkLTQ1OTgtOTEwZS0zNjNjYmExYjZkNWUiLCJuYmYiOjE3MTk5MjY1OTksInNjcCI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJvZmZsaW5lX2FjY2VzcyJdLCJzdWIiOiJjNDZmMzc0Ny0yY2QxLTRjMzgtODE3OS01MTcwYmQ2NjJmOGUifQ.NfUjWsgYsaOIILWeY9jrZDPfXBl6AuMf4vf52f1nJzUc4pixPVjxSG1_GSnZYQcksNtEic5q3Is0cjU1HCpipRsdpp0bRk4I4FZGOCbF6R-ZCSk1DvBhnLCROHGpC0761sPSxshOQo3GsouiNetDXmhZy1t3RQSywm3teM1GdFhyQUCwPIx-txnOOHbMU8mHRuHvpCaaH9KmwdA3-jRIEta …
```
> Add client_id to access token's aud

- docker/hydra/hydra.yml
- rockcraft.yaml
With https://github.com/canonical/identity-platform-login-ui-operator/pull/110 merged, we no longer need to inject the certificates on image build time.
This change reduces the image size from 63MB to 26MB
Closes #251
> Remove certs from rock

- docker/kratos/identity.schema.json
- docker/kratos/kratos.yml
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- ui/components/Flow.tsx
- ui/components/NodeInput.tsx
- ui/components/NodeInputButton.tsx
- ui/components/NodeInputPassword.tsx
- ui/components/NodeInputSubmit.tsx
- ui/components/NodeInputText.tsx
- ui/components/NodeInputUrl.tsx
- ui/pages/login.tsx
- ui/pages/setup_passkey.tsx
- ui/static/sass/styles.scss
```
make npm-build build
export KRATOS_PUBLIC_URL="http://localhost:4433"
export HYDRA_ADMIN_URL="http://localhost:4445"
export BASE_URL="http://localhost:4455"
export PORT="4455"
export TRACING_ENABLED="false"
export LOG_LEVEL="debug"
export AUTHORIZATION_ENABLED="false"
go run . serve
docker-compose -f docker-compose.dev.yml up --build --force-recreate --remove-orphans
```
```
docker exec <hydra-container> \
hydra create client \
--endpoint http://127.0.0.1:4445 \
--name grafana \
--grant-type authorization_code,refresh_token \
--response-type code,id_token \
--format json \
--scope openid,offline_access,email \
--redirect-uri http://localhost:2345/login/generic_oauth
docker run -d --name=grafana -p 2345:2345 --network identity-platform-login-ui_intranet \
-e "GF_SERVER_HTTP_PORT=2345" …
```
> Add passwordless webauthn support

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- ui/pages/setup_secure.tsx
IAM-1039
The issue is fixed by passing the original return to, to the settings flow. I moved some stuff around, to more clearly separate the responsibilities of the frontend and the backend. 
There is some reload happening in the `setup_secure` page when you get there (you momentarily see the spinning thingy). Not sure how to fix it (@edlerd please have a look)
SInce Natalia is not here this week @edlerd and @BarcoMasile please try it out, as I may have broken something
> Fix redirect on first login

- ui/pages/reset_email.tsx
- ui/pages/reset_password.tsx
- ui/pages/setup_backup_codes.tsx
- ui/pages/setup_passkey.tsx
- ui/pages/setup_secure.tsx
- fix(request) avoid using request url in the ui.
fixes #289
> fix(request) avoid using request url in the ui. fixes #289

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- pkg/kratos/interfaces.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- ui/pages/login.tsx
IAM-1114
Based on https://github.com/canonical/identity-platform-login-ui/pull/292
I made some changes to how the login flows are created in the backend, @edlerd (and @natalian98) please have a look and try it out. If this is fine, @edlerd feel free to either merge this to your branch or just push any necessary changes to this branch.
Cases that should be tested for this PR:
- First time login/authenticator setop
- Inserting username/password, going back from totp page, going forward and inserting code
- Inserting username/password, going back from totp page, inserting username/password again, inserting code
- Inserting username/password, going back from totp page, logging in with github
All the above should result in the user being redirected back to the application
> Sign in with security key not working if email is cached

- pkg/kratos/service.go
- ui/pages/setup_backup_codes.tsx
After the recent changes, setting up the backup codes was broken.
If you clicked on the `generate backup codes` button, nothing would happen. This PR fixes that
> Fix backup codes setup

- pkg/ui/handlers.go
- fix backup codes download was broken due to content security policy being too strict.
fixes #314
> fix backup codes download was broken due to content security policy

- ui/components/NodeInputEmail.tsx
- ui/components/NodeInputSubmit.tsx
- ui/pages/reset_email.tsx
- add the back button (it should just redirect to the login url)
- rename Submit to Reset password
- make sure the field doesn't show the error message once you click on the button
fixes #322
Skipped the "refactor the "Check your email" screen to contain the email address typed in the previous step" as per #322. 
Because 1. we don't know the email in the 2nd step and 2. the email does not contain any url, only the code to enter. So we need to keep the step with the input box.
> improve ui for reset password

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
IAM-1152
With this change, if you try to access localhost:4455/ui/login, the backend will return an error (400) and the browser will be redirected to the error page.
Closes #329
> Return error if no login_challenge or return_to

- docker-compose.yml
This PR adds a missing environment variable `KRATOS_ADMIN_URL` to the docker compose file.
> chore: update `docker-compose.yml`

- README.md
- cmd/serve.go
- docker-compose.yml
- internal/config/specs.go
- pkg/extra/service.go
- pkg/kratos/cookies.go
- pkg/kratos/cookies_test.go
- pkg/kratos/encryption.go
- pkg/kratos/encryption_test.go
- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- pkg/kratos/interfaces.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- pkg/web/router.go
IAM-1127
Fetch the hydra login request and check the `Skip` value to decide whether we should accept it if a session exists. Otherwise (if this isn't a hydra flow or if there is no session) we leave it to Kratos. This fixes the issue where `max_age` was not respected.
Closes #300
> Check hydra request skip value

- .github/workflows/publish.yaml
[IAM-1182](https://warthogs.atlassian.net/browse/IAM-1182): drop patch to allow cve patching within the same oci artifact tag
[IAM-1182]: https://warthogs.atlassian.net/browse/IAM-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: drop patch from oci artifact versioning

- pkg/kratos/cookies.go
- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
fixes https://github.com/canonical/identity-platform-login-ui/issues/371
> fix: do not enforce re-authentication when user was offered to regenerate backup codes

- ui/components/NodeInputEmail.tsx
> fix(reset) validate email on reset password, avoid submitting with an invalid email address

- cmd/serve.go
- docs/sequencing.md
- internal/config/specs.go
- pkg/extra/handlers.go
- pkg/extra/handlers_test.go
- pkg/kratos/handlers.go
- pkg/kratos/interfaces.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- pkg/web/router.go
- ui/pages/consent.tsx
- ui/util/handleFlowError.ts
This PR adds support for OIDC and WebAuthn sequencing.
Follow the [doc](https://github.com/canonical/identity-platform-login-ui/blob/10b9055ed36d67600f4779c6c8b812591843e549/docs/sequencing.md) to set up a testing environment for this case.
a. User has no key set up
b. User already has a webauthn key
The "I want to use another method" link must be removed, I'll open an issue for it.
> Support OIDC and WebAuthn sequencing for aal2

- pkg/status/handlers.go
- pkg/status/handlers_test.go
- pkg/web/router.go
- adds a `GET /api/v0/app-config` endpoint exposing the `OIDC_WEBAUTHN_SEQUENCING_ENABLED` flag value
> feat: add endpoint to expose application info

- docker/kratos/kratos.yml
This PR changes the default return url for webauthn method, so that the user remains on the setup page after removing or adding a key. This will not influence any redirect when setup is enforced during login.
fixes https://github.com/canonical/identity-platform-login-ui/issues/381
I will open another PR to reflect this in Kratos charm.
> ci(docker): change default settings redirect url for webauthn method

- ui/components/NodeInputButton.tsx
- ui/pages/login.tsx
- ui/util/constants.ts
- ui/util/webauthnAutoLogin.tsx
- improve UX for sequenced login
- auto redirect to OIDC provider if it is the only login option
- add checkbox to automatically open the passkeys dialogue on landing on next login. Storing the state in local storage.
To-do: blocked by receiving the status from the backend if sequenced login is enabled
> feat(ui) improve sequenced login ux

- .github/workflows/stale.yaml
Setup the [Stale action](https://github.com/actions/stale) to run every work day at 7 AM.
The current configuration allows for 60 day before labeling an issue as "stale", and 10 days before closing it.
Right now it will consider only issues, and only ones created after today.
This is to avoid disrupting our status quo.
If this is accepted then I'll proceed with the Admin UI repo as well.
> Setup stale action

- pkg/kratos/handlers.go
- pkg/kratos/handlers_test.go
- pkg/kratos/interfaces.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
- ui/pages/consent.tsx
- ui/pages/login.tsx
- ui/util/handleFlowError.ts
IAM-1286
Use `ErrorBrowserLocationChangeRequired` only in the service layer, this is a always converted to `BrowserLocationChangeRequired` before being returned to the handler. Only `BrowserLocationChangeRequired` should be used in the handler from now on. The frontend now has to handle only `BrowserLocationChangeRequired` responses.
All redirect responses to XHR will now return `200 OK`, also thought about using `422` to have similar behavior to kratos. IMO It does not really matter as long as we have a consistent behavior in backend-frontend communications. (cc @natalian98 if you have a suggestion/preference in this)
> Uniform POST response redirection

- pkg/kratos/handlers.go
- pkg/kratos/service.go
- pkg/kratos/service_test.go
This PR addresses the "Account already exists" case from https://github.com/canonical/identity-platform-login-ui/pull/731#pullrequestreview-3183585923. The backend will return an error when a duplicate account is detected.
Duplicate identifiers are detected as part of `PostSettingsPrePersistHooks`. After signing in at the external IdP, Kratos returns a 200 with an error in the settings flow `ui.nodes.messages` object (see https://www.ory.sh/docs/kratos/reference/api#tag/frontend/operation/getSettingsFlow). This is similar to how we handle some [recovery](https://github.com/canonical/identity-platform-login-ui/blob/a871b592552d7d40d6fe1a6f4ab03f6acce3375c/pkg/kratos/service.go#L373-L381) flow errors.
> feat: handle duplicate identifier error in settings flow
