canonical/identity-platform-login-ui

main.go
Add return_to to create browser login flow and add BASE_URL config
=> Add return_to to create browser login flow

ui/pages/error.tsx, ui/pages/index.tsx, ui/pages/login.tsx, ui/pages/registration.tsx
* Fix a bug introduced with [a recent PR](https://github.com/canonical/identity-platform-login-ui/pull/48), where the values received from kratos are not properly unpacked in the ui.
=> fix(ui) unpack values received from kratos

ui/package-lock.json, ui/package.json
- drop vulnerable deps
- update ui deps
=> fix(ui-deps) drop vulnerable dependencies from react-script, update ui deps

README.md
IAM-350: document changes to the environment variables
=> docs: IAM-350 - add environemnt config documentation

.github/workflows/ci.yaml
=> ci: publish on tag

pkg/kratos/handlers.go, pkg/kratos/handlers_test.go, pkg/kratos/interfaces.go, pkg/kratos/service.go, pkg/kratos/service_test.go
Proxy only the cookies.
Closes #79.﻿
=> Copy only cookies in proxied requests

pkg/status/handlers.go
Fix for missing timeout in the deep check handler in pkg/status.
=> deepcheck handler timeout

pkg/kratos/handlers.go, pkg/kratos/handlers_test.go
Fix for a bug in a handler starting a browser login flow with Kratos.
=> fix-kratos-handler

cmd/main.go, internal/config/specs.go, internal/hydra/client.go, internal/kratos/client.go
=> Add debug flag

README.md, docker-compose.dev.yml, docker/kratos/kratos.yml
IAM-616
Configure the docker-compose kratos to use github
=> GitHub integration

ui/package-lock.json, ui/package.json
=> Update ui dependencies

ui/pages/device_code.tsx
Needed to work when running under a path
=> Use relative path for device callback

.markdownlint.yaml, .markdownlintignore, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, renovate.json, ui/README.md
This pull request tries to:
- Add pre-commit hooks
- Use Renovate to upgrade pre-commit hooks
- Format documentation to follow lint rules
=> chore: add pre-commit hooks

ui/pages/login.tsx
- Hide passkey option in webauthn is not configured
fixes #277 WD-15073
=> Hide passkey option in case it is disabled

pkg/kratos/handlers.go, pkg/kratos/handlers_test.go
IAM-1044
This is hacky, but I don't think there is a better way to implement it.
Fixes https://github.com/canonical/kratos-operator/issues/259
=> Delete session before recovery

ui/pages/login.tsx
- Display error when the login flow is missing or invalid.
fixes #281
=> Display error when the login flow is missing or invalid.

pkg/kratos/handlers.go, pkg/kratos/service.go, pkg/kratos/service_test.go, ui/pages/reset_password.tsx, ui/pages/setup_backup_codes.tsx, ui/pages/setup_passkey.tsx
- fix sign in without a challenge
- i.e. on hitting the reset_password or other settings URLs directly
fixes #247
=> fix sign in without a challenge

ui/components/NodeInputPassword.tsx, ui/components/NodeInputSubmit.tsx, ui/components/NodeInputText.tsx, ui/components/NodeInputUrl.tsx, ui/static/sass/styles.scss
- fix ui layout and tab index of login page.
fixes #291
=> fix ui layout and tab index of login page.

ui/components/NodeInputSubmit.tsx, ui/util/replaceAuthLabel.ts
- feat ui: link to use authenticator app instead in screen asking for a backup code
fixes #293
=> feat ui: link to use authenticator app instead in screen asking for a backup code

ui/pages/setup_complete.tsx, ui/pages/setup_secure.tsx
- Ensure a completion message is present after setting up totp
- Automatically redirect back to the application
- Fix wrong page URL replacement, when arriving at the setup secure page.
fixes #302
=> Ensure a completion message is present after setting up totp.

pkg/kratos/handlers.go, pkg/kratos/handlers_test.go, ui/pages/backup_codes_regenerate.tsx, ui/pages/setup_backup_codes.tsx, ui/pages/setup_secure.tsx
- fix first time redirect after setting up totp
fixes #319
=> fix first time login redirect

ui/components/NodeInputEmail.tsx, ui/pages/reset_email.tsx, ui/pages/reset_password.tsx, ui/pages/setup_backup_codes.tsx, ui/pages/setup_passkey.tsx, ui/pages/setup_secure.tsx
- fix reset email flow
- ensure all flows have the flow id correctly set when we create a flow on landing.
fixes #315
fixes #322
=> fix reset email flow

ui/components/NodeImage.tsx, ui/components/NodeText.tsx
- fix ui for totp setup screen, add separators
fixes #324
=> fix ui for totp setup screen, add separators

docs/security.md
This PR adds the security documentation reviewed by the security team.
=> docs: add security overview

cmd/serve.go, internal/config/specs.go, internal/logging/logger.go, internal/logging/logger_test.go
IAM-1229
Do not write logs to disk, the charm will need to migrate to `LogForwarder`
=> Do not write logs to file

pkg/extra/service.go, pkg/extra/service_test.go
IAM-1225
This reverts commit 20fed796d51fff3689ea169e8fddb58c0dfcb5f3.
Closes #373
=> Revert "fix: add client id to at aud"

rockcraft.yaml
=> build: add security manifest to rock

ui/pages/login.tsx, ui/tests/helpers/login.ts, ui/util/constants.ts
=> fix(ui) use e-mail as label consistently, fixes #380

ui/components/NodeInputText.tsx
=> fix(ui) ensure errror messages start with an uppercase letter.

ui/components/NodeInputText.tsx, ui/pages/login.tsx
=> fix(security-key) improve ux when email does not have a security key set up

docker-compose.dev.yml
Upgrade docker dev setup openfga to v1.8.4 for ListUsers API availability
=> Upgrade docker dev setup openfga to v1.8.4 for ListUsers API availability

go.mod, go.sum, internal/hydra/client.go, internal/hydra/device.go, internal/hydra/interfaces.go, pkg/device/interfaces.go, pkg/device/service.go, pkg/device/service_test.go, pkg/extra/interfaces.go, pkg/extra/service.go, pkg/extra/service_test.go, pkg/kratos/interfaces.go, pkg/kratos/service.go, pkg/kratos/service_test.go, pkg/status/service.go, pkg/status/service_test.go, pkg/web/router.go
=> fix: update hydra sdk

go.mod, go.sum, internal/openfga/client.go
=> fix: update openfga sdk

ui/pages/login.tsx
* ensure api call to identify sequencing is enabled works when deployed within a subfolder
* simplify base url for kratos api override
fixes WD-19160
=> Use relative path for api access in login.tsx to simplify

pkg/kratos/service.go
This pull request aims to resolve the https://github.com/canonical/identity-platform-login-ui/issues/374. However, I decided to keep using the custom one, and not use the `SessionAuthenticationMethod` in the krato's SDK for the following reasons (Let me know if I'm off the road):
- It's not necessary because we only care about the authentication method that the user selects in the flow.
- Based on what I understand in the SDK's source code, the `SessionAuthenticationMethod` is to provide information about the authentication method that **_WAS_** used in the authenticated session.
=> fix: clean the request body parsing in login & settings flow

cmd/serve.go, internal/config/specs.go, pkg/status/handlers.go, pkg/status/handlers_test.go, pkg/web/router.go, ui/pages/setup_passkey.tsx
=> Make support email configurable
